# Generated by Django 5.0.2 on 2024-02-09 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=255)),
                ('spotify_artist_uri', models.URLField()),
                ('apple_music_artist_uri', models.URLField()),
                ('youtube_music_channel_uri', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('total_tracks', models.IntegerField()),
                ('spotify_album_uri', models.URLField()),
                ('apple_music_album_uri', models.URLField()),
                ('youtube_music_album_uri', models.URLField()),
                ('artist_id', models.ManyToManyField(to='sound_central_app.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=255)),
                ('duration_ms', models.IntegerField()),
                ('explicit', models.BooleanField()),
                ('spotify_track_uri', models.URLField()),
                ('apple_music_track_uri', models.URLField()),
                ('youtube_music_track_uri', models.URLField()),
                ('track_number', models.IntegerField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sound_central_app.album')),
                ('artists', models.ManyToManyField(to='sound_central_app.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=255)),
                ('playlist_description', models.TextField()),
                ('playlist_track_length', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track_id', models.ManyToManyField(to='sound_central_app.track')),
            ],
        ),
    ]
