# Generated by Django 5.0.2 on 2024-02-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound_central_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_id',
            new_name='artists',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='track_id',
            new_name='tracks',
        ),
    ]
