# Generated by Django 5.0.2 on 2024-02-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_central_app', '0002_rename_artist_id_album_artists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='apple_music_album_uri',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='spotify_album_uri',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='total_tracks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='youtube_music_album_uri',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='apple_music_artist_uri',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_artist_uri',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='youtube_music_channel_uri',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_track_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='apple_music_track_uri',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration_ms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_track_uri',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='youtube_music_track_uri',
            field=models.URLField(null=True),
        ),
    ]
