# Generated by Django 5.0.2 on 2024-02-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_central_app', '0003_alter_album_apple_music_album_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='apple_music_artist_uri',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_artist_uri',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='youtube_music_channel_uri',
            field=models.URLField(blank=True, default=''),
        ),
    ]
