# Generated by Django 5.0.2 on 2024-02-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_central_app', '0004_alter_artist_apple_music_artist_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='apple_music_album_uri',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='spotify_album_uri',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='total_tracks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='youtube_music_album_uri',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_track_length',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='apple_music_track_uri',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration_ms',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_track_uri',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_number',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='track',
            name='youtube_music_track_uri',
            field=models.URLField(blank=True, default=''),
        ),
    ]
