# Generated by Django 5.0.2 on 2024-02-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_central_app', '0005_alter_album_apple_music_album_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
