# Generated by Django 5.0.2 on 2024-02-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_central_app', '0006_playlist_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
